---
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  global:
    - secure: LcBq5R5DcX7Vtdiqw3VRRHNpkf0+iuQxa2Rg1HaFI+5n3A3fAXOPezoONRNqTLUDRoVpQ6DwesVaSm2TgzytopqDzmXDg06ccuY/op9vXYau791/XGkGPH6gZR46Cv4paqYE6y/XgYcPjIC2J+gAOzjpjON7KC1Gnaf+mYYhgeh+RYxhoQBO5fTczJSgVPzRL5YPrPCr5lZ6UJp+agoSVAKfZjSMRESiWIA4iaC7GPDvnR6eK2kR1sXzuOR0gBQMyBO0Ole3SRWw+QpDnvHl/g8uIF8J+kHXxxSVYS4EXWstaN7+lDd7dF+stwjHsfLc7UTAoiGpcsJhiqKQ3UBeVbkaicpEnyYDNeTOfgI0UbYT8D/DSZ0fVpPA0mTadA3J0YGsPOpdf8UNBEOUGxmTqG7EPou7dkFI7eVEdLiyQ/Tuz45oSJp3HqGFtiFWiMJEJzXIBXEKcViFEio1F9Slemwg8Yp75IBefs9YIV/+0tHXrIVPULuSxpaflSVIkol/wdmQlkie1we7IeYBUfjB86YJGsF/kiRi5meoiJI8IpHWAkTKGPvFWgqiVmGeyZHueyxKi73IeqBrgS3VvUgi0Xbq2QlsDgjk+zASTJ7KUtHaOHr0yuTbvElbb/wsv5ojSpDvUEp3smrrsVcCa1RyE1CqsBvVbYiZlv1d5dqXsV8=
    - md_ignore: R1
before_install:
install:
  - pip install -r requirements.txt
before_script:
  - for file in `find . -maxdepth 2 -name "*.md"` ;  do markdownlint --ignore $md_ignore $file ; done
script:
  - molecule dependency
  - molecule lint
  - molecule create
  - travis_wait 30 molecule converge
  - travis_wait 30 molecule idempotence
  - molecule verify
  - cd $TRAVIS_BUILD_DIR
after_success:
  - docker commit voms-clients-centos6 quay.io/egi/voms-client:centos6
  - docker commit voms-clients-centos7 quay.io/egi/voms-client:centos7
  - docker login -u="egi+packerbot" -p="$QUAY_PASSWORD" quay.io
  - docker push quay.io/egi/voms-client:centos6
  - docker push quay.io/egi/voms-client:centos7
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: PmigS5k2M2LvuC5nmdJaLNild30yiH7M3Yab4xcSN9IQbWNsM3mbITpaMBiatcgLs75AvzlSM0YqBuyhU5HZ2kDGoQaEVQ4BIqTX+OeLMvsD9duJGYYF71kvOUjlhxdwJHGMkWqf8UmdMWGLzSivGxh1Vt6ow6ZQwj4TFaeOHgjpmp3/uxzK1WD+MzknBBtcmBYhrk6RPuQJWjAq5qr8M2AjLXoz3m4JrnP+ZEhGmHgAqcjsD1pS/xgA2FsicGjc3GLuZwEGbgmPpC9vuT/bJ0HzGhSBUzJbuL/pUxVAroS/EH/TWrYwmSZL9ZZOIq+xQG0GQ0AC8RGkZeMnR+l9IO7uyaM8j6cOwKixRQgm3xzEH0QXdWcjgaVxCFkGn+GDO1m6SdYSrlb/C71lZPmMUzX3HVbUG9KW4S+RKoCfJNYsB03qRsRkafMCwgHsZ8TkRBvi9mxcZm2QJKfU6ltELn2bvyPWH2mc93vGtHnfc+cBzmNn1u4brh6Cmva5LodqzxfqzciCV1fqFkyqH8PEZpGUIM9/78/VP6731o1ZzHq+sm+QHi6Gb6rllBRcqoW1aKA9v8w+ZEYo8GPsnDrJD4QX5vNFY/4bLjAuhZexAiCL/I0BwN6r+JYvsggUFNQxvnaWGtzNyJ9DaVzf0zMasoSwF+OoZYvRdadPjQPs06k=
