---
# configure tasks for voms
- name: Ensure Required VOMS directories
  file:
    path: "{{ item }}"
    state: "directory"
  loop:
    - "{{ voms_dir }}"
    - "{{ vomses_dir }}"

- name: Get all the VOMS info
  uri:
    method: GET
    url: "{{ lavoisier.base_url  }}/{{ lavoisier.vo_id_card_endpoint }}"
  register: vo_voms

- name: Create LSC directories
  file:
    path: "{{ voms_dir }}/{{ item }}"
    state: directory
  loop: "{{ vo_voms | json_query('json.voVoms[*].name') }}"


# LSC files should have the format:
# certificate DN
# CA signing authority
# Path is /etc/vomsdir/vo-name/voms-host.lsc

- name: Ensure LSC files present
  file:
    path: "{{ voms_dir }}/{{ item.name}}/{{ item.voms.hostname }}.lsc"
    content: >
      "{{ item.voms.DN}}"
      "{{ item.voms.CA_DN}}"
