---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/collections.yml
driver:
  name: docker
scenario:
  name: default
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
  flake8 --config .github/linters/.flake8
platforms:
  - name: voms-clients-almalinux9
    image: quay.io/egi/umd5:almalinux9
provisioner:
  name: ansible
  config_options:
    defaults:
      force_color: true
      callback_whitelist: yaml
      stdout_callback: community.general.yaml
      bin_ansible_callbacks: true
verifier:
  name: testinfra
  options:
    verbose: true
    color: "yes"
    capture: "no"
